server {
    listen 80;
    listen [::]:80;
    server_name cargo.gnpsistemas.com.br;

    location /static/ {
        alias /var/www/static/;
        autoindex off;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Bloqueia qualquer outra coisa que não seja estático neste container
    location / {
        return 404;
    }
}