# Generated by Django 5.2.8 on 2026-01-28 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('entities', '0008_remove_entity_is_carrier_remove_entity_is_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codification', models.CharField(max_length=255)),
                ('max_length', models.IntegerField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tenant', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_code', models.CharField(db_index=True, max_length=120)),
                ('product_description', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('activated', 'Activated'), ('stocked', 'Stocked'), ('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='generated', max_length=20)),
                ('tracking_code_origin', models.CharField(choices=[('carrier', 'Carrier'), ('client', 'Client')], default='client')),
                ('length', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_packages', to='entities.party')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stored_packages', to='entities.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tenant', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhysicalSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space_type', models.CharField(choices=[('WAREHOUSE', 'warehouse'), ('ZONE', 'zone'), ('AISLE', 'aisle'), ('RACK', 'rack'), ('LEVEL', 'level'), ('BIN', 'bin'), ('FLOOR', 'floor'), ('DOCK', 'dock'), ('STAGING', 'staging')], max_length=20)),
                ('code', models.CharField(max_length=50)),
                ('max_volume', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entities.party')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stock.physicalspace')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tenant', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_volume', models.DecimalField(decimal_places=3, max_digits=14)),
                ('allocated_weight', models.DecimalField(decimal_places=3, max_digits=14)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='stock.package')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='stock.physicalspace')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tenant', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceCapacitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_volume', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('used_weight', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.physicalspace')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tenant', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackingSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_value', models.BigIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tenant', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='physicalspace',
            index=models.Index(fields=['tenant', 'space_type'], name='stock_physi_tenant__02aa2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='physicalspace',
            unique_together={('tenant', 'parent', 'code')},
        ),
        migrations.AddIndex(
            model_name='spaceallocation',
            index=models.Index(fields=['tenant', 'space'], name='stock_space_tenant__6fbd58_idx'),
        ),
        migrations.AddIndex(
            model_name='spaceallocation',
            index=models.Index(fields=['tenant', 'package'], name='stock_space_tenant__cd9fc7_idx'),
        ),
    ]
