# Generated by Django 5.2.10 on 2026-02-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_due_day',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='value_per_read_package',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10),
        ),
    ]
