# Generated by Django 5.2.10 on 2026-01-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_rename_is_supplier_entity_is_shipping_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='is_member_of_tenant',
            new_name='is_branch',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='is_accessible',
            new_name='is_system',
        ),
        migrations.AddField(
            model_name='entity',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
