# Generated by Django 5.2.10 on 2026-01-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_rename_is_member_of_tenant_entity_is_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='fantasy_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
