# Generated by Django 5.2.10 on 2026-01-23 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_entity_fantasy_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='is_shipping_company',
            new_name='is_carrier',
        ),
    ]
