# Generated by Django 5.2.10 on 2026-01-24 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_rename_is_shipping_company_entity_is_carrier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='is_main',
        ),
        migrations.AddField(
            model_name='entity',
            name='economic_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='economic_groups', to='entities.entity'),
        ),
    ]
