# Generated by Django 5.2.8 on 2026-01-28 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('entities', '0007_remove_entity_is_main_entity_economic_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='is_carrier',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='is_client',
        ),
        migrations.AddField(
            model_name='entityaddress',
            name='city_code',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entityaddress',
            name='country_code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='cpforcnpj',
            field=models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], default='CNPJ', max_length=4),
        ),
        migrations.AlterField(
            model_name='entityaddress',
            name='state',
            field=models.CharField(max_length=5),
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('client', 'Client'), ('supplier', 'Supplier'), ('carrier', 'Carrier'), ('sender', 'Sender'), ('receiver', 'Receiver'), ('warehouse', 'Warehouse')], default='client', max_length=20)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='entities.entity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tenant', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'unique_together': {('entity', 'role')},
            },
        ),
    ]
