# Generated by Django 5.2.8 on 2026-01-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_remove_entity_is_carrier_remove_entity_is_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('carrier', 'Carrier'), ('sender', 'Sender'), ('receiver', 'Receiver'), ('warehouse', 'Warehouse')], default='client', max_length=20),
        ),
    ]
