# Generated by Django 5.2.8 on 2026-02-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_alter_party_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('carrier', 'Carrier'), ('sender', 'Sender'), ('receiver', 'Receiver')], default='client', max_length=20),
        ),
    ]
