# Generated by Django 5.2.10 on 2026-02-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_alter_party_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('carrier', 'Carrier'), ('sender', 'Sender'), ('receiver', 'Receiver'), ('supplier', 'Supplier')], default='client', max_length=20),
        ),
    ]
