# Generated by Django 5.2.10 on 2026-04-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_alter_party_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='conference_sla',
            field=models.IntegerField(default=1800, help_text='Conference SLA in seconds'),
        ),
    ]
