# Generated by Django 5.2.8 on 2026-01-28 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_remove_entity_is_carrier_remove_entity_is_client_and_more'),
        ('logistics', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='carrier_entity',
            new_name='carrier',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='client_entity',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='source_entity',
        ),
        migrations.AddField(
            model_name='conference',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_conferences', to='entities.party'),
        ),
    ]
