# Generated by Django 5.2.8 on 2026-01-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_rename_carrier_entity_conference_carrier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='items_added',
            field=models.BooleanField(default=False),
        ),
    ]
