# Generated by Django 5.2.8 on 2026-01-30 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_remove_entity_is_carrier_remove_entity_is_client_and_more'),
        ('logistics', '0004_conference_items_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='next_destiny',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='next_destiny_conferences', to='entities.party'),
            preserve_default=False,
        ),
    ]
