# Generated by Django 5.2.8 on 2026-01-30 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_remove_entity_is_carrier_remove_entity_is_client_and_more'),
        ('logistics', '0005_conference_next_destiny'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='client',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='next_destiny',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='supplier',
        ),
        migrations.AddField(
            model_name='conference',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='destination_conferences', to='entities.party'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='flow_type',
            field=models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound'), ('transfer', 'Transfer')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='origin_conferences', to='entities.party'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='parent_conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_conferences', to='logistics.conference'),
        ),
    ]
