# Generated by Django 5.2.8 on 2026-01-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_remove_conference_carrier_remove_conference_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='flow_type',
            field=models.CharField(choices=[('load', 'Load / Embarque físico'), ('unload', 'Unload / Desembarque físico'), ('transit', 'Transit / Passagem')], max_length=20),
        ),
    ]
