# Generated by Django 5.2.8 on 2026-01-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_conference_flow_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='flow_type',
            field=models.CharField(choices=[('load', 'Load / Embarque físico'), ('unload', 'Unload / Desembarque físico')], max_length=20),
        ),
    ]
