# Generated by Django 5.2.8 on 2026-01-30 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_alter_conference_flow_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='flow_type',
            new_name='event_type',
        ),
    ]
