# Generated by Django 5.2.8 on 2026-01-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_rename_flow_type_conference_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='event_type',
            field=models.CharField(choices=[('load', 'Embarcar no veículo'), ('unload', 'Desembarcar do veículo')], max_length=20),
        ),
    ]
