# Generated by Django 5.2.8 on 2026-02-02 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_alter_conference_event_type'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceitem',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='logistics.conference'),
        ),
        migrations.AlterField(
            model_name='conferenceitem',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conference_packages', to='stock.package'),
        ),
    ]
