# Generated by Django 5.2.8 on 2026-02-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_alter_conferenceitem_conference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='items_added',
        ),
        migrations.AddField(
            model_name='conference',
            name='mode',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write')], default='read', max_length=20),
        ),
    ]
