# Generated by Django 5.2.8 on 2026-02-04 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_conference_started_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceitem',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='logistics.conference'),
        ),
    ]
