# Generated by Django 5.2.10 on 2026-02-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_alter_conferenceitem_conference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='event_type',
            field=models.CharField(choices=[('load', 'Load in the vehicle'), ('unload', 'Unload from the vehicle')], max_length=20),
        ),
    ]
